### PR TITLE
[MRG+2] fix comments and doc which refer to n_fits as n_iter

### PR DESCRIPTION
**Pull request by anne-decusatis**
# Description

Please include a summary of the change and which issue is fixed:

When reading the docs I noticed that n_fits (which is used to determine the number of test iterations used to fit in random search cases) is sometimes referred to as n_iter. It looks like n_fits is the variable name that's actually in use. I looked for usages of n_iter and changed the ones which referred to n_fits. This is a very minor change which affects a few comments, one reference in documentation, and the text of a single error that's thrown if n_fits is negative. Please feel free to edit or reject.

Fixes # n/a
This is such a minor change (at first I thought it was doc-only) that I didn't file an issue first. Please let me know if I need to!

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Documentation change

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
Provide instructions so we can reproduce. Please also list any relevant details
for your test configuration

I haven't run tests locally because this doesn't really change any functionality - I expect the CI to succeed, if it doesn't I can debug locally. 

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [n/a] I have added tests that prove my fix is effective or that my feature works
- [n/a] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by anne-decusatis** [comment]
Looks like the failing tests are failing on `make clean`. I'm not familiar with the setup of this repo but it seems likely to me that it's not related to this change.

**Review by tgsmith61591 — APPROVED** [review]
Thanks for the PR!

**Comment by aaronreidsmith** [comment]
The CI/CD is broken because of a new setuptools version that was released recently. I have a fix up in #491. We'll merge your fix in once we get that one merged in!

**Review by aaronreidsmith — APPROVED** [review]

**Comment by aaronreidsmith** [comment]
@anne-decusatis can you update your branch to have the latest master changes? GitHub won't let me merge this without all the status checks 😬

**Pull request merged**
