### PR TITLE
[MRG+2] Fix conda deployments

### LINKED ISSUE #298: Conda Install Failing
**Describe the bug**
```bash
conda install -c alkaline-ml pmdarima
```
The above line is failing for 2 reasons:

1. It attempts to install for py3.6 regardless of what version you are actually using

2. You get an import error when you actually do download it

**To Reproduce**  
See above

**Expected behavior**
Install finds right version and actually installs it

**Actual behavior**
See above

**Additional context**
This is just an issue to get ahead of the curve and show it is a known bug. We are actively working on a fix. In the meantime, use `pip install pmdarima` within your conda environment

### PR DESCRIPTION
**Pull request by aaronreidsmith**
# Description

We ran into a bunch of issues when deploying 1.5.3. The only one that is still affecting us is that our conda builds are broken. A normal conda build should have both an `info` directory and a `lib` directory (`Lib` on Windows). Here is a version of `pmdarima` on conda that we did _not_ create:

```
$ tar -tf pmdarima-1.2.0-py36h56e435c_7.tar.bz2 
info/hash_input.json
info/index.json
info/git
info/has_prefix
info/about.json
info/files
info/paths.json
lib/python3.6/site-packages/pmdarima/preprocessing/exog/tests/__init__.py
info/test/run_test.py
lib/python3.6/site-packages/pmdarima/__check_build/tests/__init__.py
lib/python3.6/site-packages/pmdarima/datasets/tests/__init__.py
lib/python3.6/site-packages/pmdarima/_build_utils/tests/__init__.py
lib/python3.6/site-packages/pmdarima/preprocessing/endog/__init__.py
lib/python3.6/site-packages/pmdarima/preprocessing/exog/__init__.py
lib/python3.6/site-packages/pmdarima/preprocessing/__init__.py
lib/python3.6/site-packages/pmdarima/datasets/__init__.py
lib/python3.6/site-packages/pmdarima/arima/tests/test_c_arima.py
lib/python3.6/site-packages/pmdarima/compat/pandas.py
lib/python3.6/site-packages/pmdarima/compat/__init__.py
lib/python3.6/site-packages/pmdarima/__check_build/tests/test_check_build.py
lib/python3.6/site-packages/pmdarima/arima/__init__.py
lib/python3.6/site-packages/pmdarima/compat/_internal.py
lib/python3.6/site-packages/pmdarima/arima/warnings.py
lib/python3.6/site-packages/pmdarima/compat/numpy.py
lib/python3.6/site-packages/pmdarima/__check_build/setup.py
lib/python3.6/site-packages/pmdarima/utils/tests/test_wrapped.py
lib/python3.6/site-packages/pmdarima/datasets/tests/test_load_datasets.py
lib/python3.6/site-packages/pmdarima/utils/tests/test_meta.py
lib/python3.6/site-packages/pmdarima/compat/tests/test_python.py
lib/python3.6/site-packages/pmdarima/preprocessing/setup.py
lib/python3.6/site-packages/pmdarima/compat/tests/test_statsmodels.py
lib/python3.6/site-packages/pmdarima/utils/__init__.py
lib/python3.6/site-packages/pmdarima/compat/statsmodels.py
lib/python3.6/site-packages/pmdarima/compat/python.py
lib/python3.6/site-packages/pmdarima/preprocessing/exog/setup.py
lib/python3.6/site-packages/pmdarima/arima/tests/test_arima_diagnostics.py
lib/python3.6/site-packages/pmdarima/decorators.py
lib/python3.6/site-packages/pmdarima/arima/setup.py
lib/python3.6/site-packages/pmdarima/preprocessing/endog/base.py
lib/python3.6/site-packages/pmdarima/setup.py
lib/python3.6/site-packages/pmdarima/compat/matplotlib.py
lib/python3.6/site-packages/pmdarima/utils/wrapped.py
lib/python3.6/site-packages/pmdarima/utils/tests/test_vis.py
lib/python3.6/site-packages/pmdarima/__check_build/__init__.py
lib/python3.6/site-packages/pmdarima/__init__.py
lib/python3.6/site-packages/pmdarima/preprocessing/exog/base.py
lib/python3.6/site-packages/pmdarima/utils/tests/test_array.py
lib/python3.6/site-packages/pmdarima/base.py
lib/python3.6/site-packages/pmdarima/preprocessing/endog/tests/test_boxcox.py
lib/python3.6/site-packages/pmdarima/arima/tests/test_approx.py
lib/python3.6/site-packages/pmdarima/_build_utils/__init__.py
lib/python3.6/site-packages/pmdarima/datasets/airpassengers.py
lib/python3.6/site-packages/pmdarima/datasets/austres.py
lib/python3.6/site-packages/pmdarima/datasets/lynx.py
lib/python3.6/site-packages/pmdarima/utils/metaestimators.py
lib/python3.6/site-packages/pmdarima/datasets/woolyrnq.py
lib/python3.6/site-packages/pmdarima/preprocessing/exog/tests/test_fourier.py
lib/python3.6/site-packages/pmdarima/datasets/heartrate.py
lib/python3.6/site-packages/pmdarima/preprocessing/base.py
lib/python3.6/site-packages/pmdarima/datasets/wineind.py
lib/python3.6/site-packages/pmdarima/arima/utils.py
lib/python3.6/site-packages/pmdarima/preprocessing/endog/boxcox.py
lib/python3.6/site-packages/pmdarima/arima/approx.py
lib/python3.6/site-packages/pmdarima/arima/tests/test_stationarity.py
lib/python3.6/site-packages/pmdarima/preprocessing/exog/fourier.py
lib/python3.6/site-packages/pmdarima/utils/array.py
lib/python3.6/site-packages/pmdarima/utils/visualization.py
lib/python3.6/site-packages/pmdarima/arima/_auto_solvers.py
lib/python3.6/site-packages/pmdarima/arima/tests/test_seasonality.py
lib/python3.6/site-packages/pmdarima/pipeline.py
lib/python3.6/site-packages/pmdarima/arima/_doc.py
lib/python3.6/site-packages/pmdarima/arima/seasonality.py
lib/python3.6/site-packages/pmdarima/arima/stationarity.py
lib/python3.6/site-packages/pmdarima/arima/auto.py
lib/python3.6/site-packages/pmdarima/arima/tests/test_arima.py
lib/python3.6/site-packages/pmdarima/arima/arima.py
lib/python3.6/site-packages/pmdarima/preprocessing/endog/tests/__init__.py
lib/python3.6/site-packages/pmdarima/utils/tests/__init__.py
lib/python3.6/site-packages/pmdarima/arima/tests/__init__.py
lib/python3.6/site-packages/pmdarima/compat/tests/__init__.py
lib/python3.6/site-packages/pmdarima-1.2.0.dist-info/AUTHORS.md
lib/python3.6/site-packages/pmdarima-1.2.0.dist-info/INSTALLER
lib/python3.6/site-packages/pmdarima-1.2.0.dist-info/WHEEL
lib/python3.6/site-packages/pmdarima-1.2.0.dist-info/LICENSE
lib/python3.6/site-packages/pmdarima-1.2.0.dist-info/METADATA
lib/python3.6/site-packages/pmdarima-1.2.0.dist-info/RECORD
lib/python3.6/site-packages/pmdarima-1.2.0.dist-info/top_level.txt
lib/python3.6/site-packages/pmdarima/utils/tests/__pycache__/__init__.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/arima/tests/__pycache__/__init__.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/compat/tests/__pycache__/__init__.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/arima/tests/__pycache__/__init__.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/utils/tests/__pycache__/__init__.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/compat/tests/__pycache__/__init__.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/preprocessing/exog/tests/__pycache__/__init__.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/preprocessing/endog/tests/__pycache__/__init__.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/preprocessing/exog/tests/__pycache__/__init__.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/preprocessing/endog/tests/__pycache__/__init__.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/datasets/tests/__pycache__/__init__.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/_build_utils/tests/__pycache__/__init__.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/__check_build/tests/__pycache__/__init__.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/datasets/tests/__pycache__/__init__.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/_build_utils/tests/__pycache__/__init__.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/__check_build/tests/__pycache__/__init__.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/compat/__pycache__/numpy.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/compat/__pycache__/numpy.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/compat/__pycache__/pandas.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/preprocessing/exog/__pycache__/__init__.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/preprocessing/endog/__pycache__/__init__.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/compat/__pycache__/pandas.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/preprocessing/exog/__pycache__/__init__.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/preprocessing/endog/__pycache__/__init__.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/preprocessing/__pycache__/__init__.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/preprocessing/__pycache__/__init__.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/datasets/__pycache__/__init__.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/datasets/__pycache__/__init__.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/arima/tests/__pycache__/test_c_arima.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/arima/tests/__pycache__/test_c_arima.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/__check_build/tests/__pycache__/test_check_build.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/arima/__pycache__/__init__.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/__check_build/tests/__pycache__/test_check_build.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/arima/__pycache__/__init__.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/compat/__pycache__/__init__.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/compat/__pycache__/_internal.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/__check_build/__pycache__/setup.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/compat/__pycache__/__init__.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/compat/__pycache__/_internal.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/__check_build/__pycache__/setup.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/datasets/tests/__pycache__/test_load_datasets.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/datasets/tests/__pycache__/test_load_datasets.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/utils/tests/__pycache__/test_wrapped.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/preprocessing/__pycache__/setup.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/utils/tests/__pycache__/test_wrapped.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/preprocessing/__pycache__/setup.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/arima/__pycache__/warnings.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/arima/__pycache__/warnings.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/compat/__pycache__/python.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/compat/__pycache__/python.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/compat/tests/__pycache__/test_python.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/compat/tests/__pycache__/test_python.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/compat/__pycache__/statsmodels.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/compat/__pycache__/statsmodels.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/preprocessing/exog/__pycache__/setup.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/arima/__pycache__/setup.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/preprocessing/exog/__pycache__/setup.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/arima/__pycache__/setup.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/utils/__pycache__/__init__.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/compat/tests/__pycache__/test_statsmodels.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/utils/__pycache__/__init__.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/compat/tests/__pycache__/test_statsmodels.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/__pycache__/setup.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/__pycache__/setup.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/__pycache__/__init__.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/arima/tests/__pycache__/test_arima_diagnostics.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/__pycache__/__init__.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/arima/tests/__pycache__/test_arima_diagnostics.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/compat/__pycache__/matplotlib.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/compat/__pycache__/matplotlib.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/__pycache__/decorators.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/__pycache__/decorators.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/utils/tests/__pycache__/test_vis.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/utils/tests/__pycache__/test_meta.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/utils/tests/__pycache__/test_vis.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/utils/tests/__pycache__/test_meta.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/__check_build/__pycache__/__init__.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/__check_build/__pycache__/__init__.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/utils/__pycache__/wrapped.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/utils/__pycache__/wrapped.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/preprocessing/endog/__pycache__/base.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/preprocessing/endog/__pycache__/base.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/utils/tests/__pycache__/test_array.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/_build_utils/__pycache__/__init__.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/utils/tests/__pycache__/test_array.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/_build_utils/__pycache__/__init__.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/arima/tests/__pycache__/test_approx.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/arima/tests/__pycache__/test_approx.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/preprocessing/exog/__pycache__/base.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/preprocessing/exog/__pycache__/base.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/preprocessing/endog/tests/__pycache__/test_boxcox.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/preprocessing/endog/tests/__pycache__/test_boxcox.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/__pycache__/base.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/__pycache__/base.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/preprocessing/exog/tests/__pycache__/test_fourier.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/preprocessing/exog/tests/__pycache__/test_fourier.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/datasets/__pycache__/airpassengers.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/datasets/__pycache__/airpassengers.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/utils/__pycache__/metaestimators.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/utils/__pycache__/metaestimators.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/datasets/__pycache__/austres.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/datasets/__pycache__/lynx.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/datasets/__pycache__/austres.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/datasets/__pycache__/lynx.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/datasets/__pycache__/woolyrnq.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/datasets/__pycache__/woolyrnq.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/datasets/__pycache__/wineind.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/datasets/__pycache__/wineind.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/arima/__pycache__/approx.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/arima/__pycache__/approx.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/datasets/__pycache__/heartrate.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/datasets/__pycache__/heartrate.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/arima/__pycache__/utils.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/arima/__pycache__/utils.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/arima/tests/__pycache__/test_stationarity.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/preprocessing/__pycache__/base.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/preprocessing/__pycache__/base.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/arima/tests/__pycache__/test_stationarity.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/arima/__pycache__/_auto_solvers.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/arima/__pycache__/_auto_solvers.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/preprocessing/endog/__pycache__/boxcox.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/preprocessing/endog/__pycache__/boxcox.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/arima/tests/__pycache__/test_seasonality.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/utils/__pycache__/array.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/utils/__pycache__/array.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/preprocessing/exog/__pycache__/fourier.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/preprocessing/exog/__pycache__/fourier.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/arima/tests/__pycache__/test_seasonality.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/utils/__pycache__/visualization.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/utils/__pycache__/visualization.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/arima/__pycache__/seasonality.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/arima/__pycache__/seasonality.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/__pycache__/pipeline.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/__pycache__/pipeline.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/arima/__pycache__/auto.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/arima/__pycache__/auto.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/arima/__pycache__/_doc.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/arima/__pycache__/_doc.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/arima/__pycache__/stationarity.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/arima/__pycache__/stationarity.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/arima/tests/__pycache__/test_arima.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/arima/tests/__pycache__/test_arima.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/arima/__pycache__/arima.cpython-37.pyc
lib/python3.6/site-packages/pmdarima/arima/__pycache__/arima.cpython-36.pyc
lib/python3.6/site-packages/pmdarima/__check_build/_check_build.cpython-36m-darwin.so
lib/python3.6/site-packages/pmdarima/preprocessing/exog/_fourier.cpython-36m-darwin.so
lib/python3.6/site-packages/pmdarima/arima/_arima.cpython-36m-darwin.so
info/recipe/conda_build_config.yaml
info/recipe/20190523.meta.yaml
info/recipe/someting_conda_build_config.yaml
info/recipe/20190525.1946.meta.yaml
info/recipe/meta.yaml
info/recipe/meta.yaml.template
info/recipe/build.sh.old
info/recipe/bld.bat.old
```

Here is one we created:

```
$ tar -tf pmdarima-1.5.3-py36.tar.bz2 
info/paths.json
info/hash_input.json
info/index.json
info/about.json
info/git
info/files
info/recipe/meta.yaml.template
info/test/run_test.sh
info/licenses/LICENSE
info/recipe/conda_build_config.yaml
info/recipe/meta.yaml
```

As you can see, ours _only_ has the `info` directory.

Here is what is included/addressed in this PR:

- Conda is silly in that when it builds, it installs to the default `site-packages` for testing, but then does not include that in the output...
    - To address this, we install to both `site-packages` and `$PREFIX/site-packages` (`$PREFIX` is a [conda env variable](https://docs.conda.io/projects/conda-build/en/latest/user-guide/environment-variables.html)). One gets tested running our unit tests, the other is bundled in the output `tar.bz2`

- Related to the above change, before deploying, we now check to make sure the output `tar.bz2` has a `lib` (or `Lib` on Windows) directory  before deploying (it is a requirement for deployment now)

- Previous iterations of this conda pipeline had 3 separate files for our operating systems. We still have 3 files, but now we have `common`, for steps shared between all operating systems, `unix` for steps shared between Linux and macOS, and `windows` for Windows. This should save us time/energy when we have to update this pipeline.

- We no longer build a wheel before building the conda distribution on Unix

- Fix silent error where `$output_file` was not defined after moving to using a separate deploy script

- Fixes our conda string to look something like this: `py37gcd6b1ea6_68` instead of `py37`

Fixes #298 

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

- [X] Unit tests pass in conda
- [X] All conda dists now have `lib` directories

# Checklist:

- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by aaronreidsmith** [comment]
@tgsmith61591 We can use the `rc` tags? That will test the deployment without deploying to the production channels

**Comment by TariqAHassan** [comment]
Hey @aaronreidsmith 

Was this fix ever pushed to the production channel?
`conda install -c alkaline-ml pmdarima` still does not work when using Python 3.7.

**Comment by aaronreidsmith** [comment]
Not quite yet, sorry for the delay! We have a couple more features/fixes before we deploy. Conda builds were new for all of the maintainers, and added in 1.5.3, so apologies for the hiccups. Use `pip install pmdarima` for now.  You can [watch for releases](https://help.github.com/en/github/receiving-notifications-about-activity-on-github/watching-and-unwatching-releases-for-a-repository#watching-releases-for-a-repository) to be notified when we get it out

**Comment by TariqAHassan** [comment]
Thanks :)

**Comment by aaronreidsmith** [comment]
@TariqAHassan I hate to be the bearer of bad news on this, but v1.6.0 will actually _not_ have conda support.

See issue #326 for details, but basically we have tried and failed several times to get this package to build properly on conda for the platforms we support on pypi. If you or anyone you know who uses the package happens to be a conda expert, help/PRs are welcome!

**Pull request merged**
